# Generated by Django 5.0.2 on 2024-02-26 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 20, 5, 14, 964958)),
        ),
    ]
